version: '3.8'

services:
  #netbox:
  #  networks:
  #    default:
  #    development:
  #      ipv4_address: 10.10.10.2
  app:
    build: .
    command: go run . worker
    develop:
      watch:
        - action: sync+restart
          path: ./
          target: /app
          ignore:
            - .git
    networks:
      default:
      development:
        ipv4_address: 10.10.10.3

networks:
  development:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24
