version: '3.8'

services:
  netbox:
    image: docker.io/netboxcommunity/netbox:v3.7.1
    networks:
      default:
      development:
        ipv4_address: 10.10.10.2

networks:
  development:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24
