// Code generated by "gen.go"; DO NOT EDIT.

package manager

import "dylaan.nl/netbox-deployer/internal/pkg/netbox"

var allNetboxModelNames []netbox.ModelName

func init() {
	allNetboxModelNames = []netbox.ModelName {
		netbox.ModelName("vminterface"),
		netbox.ModelName("vmdisk"),
		netbox.ModelName("virtualmachine"),
		netbox.ModelName("tag"),
	}
}

func hasComponent(vm netbox.VirtualMachine, event netbox.WebhookEvent) bool {
	

	

	






	

	



	

	

	



	













	

	



	









	return false
}
